jobs:
    allow_failures:
      - os: osx
      
    include:
      - stage: test
        os: osx
        language: sh
        env:
          - TOXENV=py3
          - HOMEBREW_NO_INSTALL_CLEANUP=1
          - HOMEBREW_NO_ANALYTICS=1
        before_cache:
          # - brew cleanup
          - rm -f "$HOME/Library/Caches/pip/log/debug.log"
        cache:
          directories:
            # - "$HOME/Library/Caches/Homebrew"
            - "$HOME/Library/Caches/pip"
        addons:
          homebrew:
            # update: true
            packages: python3
        before_install:
          - python3 -m pip install --upgrade virtualenv
          - virtualenv -p python3 --system-site-packages "$HOME/venv"
          - source "$HOME/venv/bin/activate"
        install: pip install -r requirements.txt
        script: echo fine