//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL; // 0x601050

// ------------------------ Functions -------------------------

// Address range: 0x400636 - 0x4006b4
int main(int argc, char ** argv) {
    // 0x400636
    __readfsqword(40);
    setbuf(g1, NULL);
    int64_t buf; // bp-152, 0x400636
    __asm_rep_stosq_memset((char *)&buf, 0, 16);
    puts("Format String");
    while (true) {
        // 0x400685
        read(0, &buf, 128);
        printf((char *)&buf);
    }
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);
// int puts(const char * s);
// ssize_t read(int fd, void * buf, size_t nbytes);
// void setbuf(FILE * restrict stream, char * restrict buf);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (5.4.0)
// Detected functions: 1
