//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_1050(void);
int64_t function_1054(void);
int64_t function_868(void);
void function_890(int32_t status);
char * function_8a0(char * dest, char * src);
int32_t function_8b0(char * s);
int32_t function_8c0(char * s);
void function_8d0(void);
int64_t * function_8e0(int64_t * addr, int32_t len, int32_t prot, int32_t flags, int32_t fd, int32_t offset);
void function_8f0(struct _IO_FILE * stream, char * buf);
int32_t function_900(char * format, ...);
int64_t * function_910(int64_t * s, int32_t c, int32_t n);
int32_t function_920(int32_t seconds);
int32_t function_930(int32_t fd, int64_t * buf, int32_t nbytes);
int32_t function_940(char * nptr);
void function_950(int32_t status);
void function_960(int64_t * d);
int64_t function_9a0(void);
int64_t function_9e0(void);
int64_t function_a30(void);
int64_t function_a70(void);
int64_t function_a7a(int64_t a1, int64_t a2);
int64_t function_a90(void);
int64_t function_b7d(int64_t * a1, int64_t a2);
int64_t function_bfa(void);
int64_t function_c44(int64_t a1);
int64_t function_e65(void);
int64_t function_ef9(void);
int64_t function_fb2(void);
int64_t function_fe0(int64_t a1, int64_t a2, int64_t a3);

// --------------------- Global Variables ---------------------

int64_t g1 = 2672; // 0x201d58
int64_t g2 = 2608; // 0x201d60
struct _IO_FILE * g3 = NULL; // 0x202020
struct _IO_FILE * g4 = NULL; // 0x202030
struct _IO_FILE * g5 = NULL; // 0x202040
char g6 = 0; // 0x202048
char * g7; // 0x202560
char * g8; // 0x202c60
int64_t g9 = 0; // 0x202c68
char * g10; // 0x202c70
char * g11; // 0x202c78
int64_t g12 = 0; // 0x202c80
char * g13; // 0x202c88
char * g14; // 0x3fc
int32_t g16;
int64_t * g15 = (int64_t *)&g4; // 0x700

// ------------------------ Functions -------------------------

// Address range: 0x868 - 0x87f
int64_t function_868(void) {
    int64_t result = 0; // 0x876
    if (*(int64_t *)0x201fe8 != 0) {
        // 0x878
        __gmon_start__();
        result = &g16;
    }
    // 0x87a
    return result;
}

// Address range: 0x890 - 0x896
void function_890(int32_t status) {
    // 0x890
    _exit(status);
}

// Address range: 0x8a0 - 0x8a6
char * function_8a0(char * dest, char * src) {
    // 0x8a0
    return strcpy(dest, src);
}

// Address range: 0x8b0 - 0x8b6
int32_t function_8b0(char * s) {
    // 0x8b0
    return puts(s);
}

// Address range: 0x8c0 - 0x8c6
int32_t function_8c0(char * s) {
    // 0x8c0
    return strlen(s);
}

// Address range: 0x8d0 - 0x8d6
void function_8d0(void) {
    // 0x8d0
    __stack_chk_fail();
}

// Address range: 0x8e0 - 0x8e6
int64_t * function_8e0(int64_t * addr, int32_t len, int32_t prot, int32_t flags, int32_t fd, int32_t offset) {
    // 0x8e0
    return mmap(addr, len, prot, flags, fd, offset);
}

// Address range: 0x8f0 - 0x8f6
void function_8f0(struct _IO_FILE * stream, char * buf) {
    // 0x8f0
    setbuf(stream, buf);
}

// Address range: 0x900 - 0x906
int32_t function_900(char * format, ...) {
    // 0x900
    return printf(format);
}

// Address range: 0x910 - 0x916
int64_t * function_910(int64_t * s, int32_t c, int32_t n) {
    // 0x910
    return memset(s, c, n);
}

// Address range: 0x920 - 0x926
int32_t function_920(int32_t seconds) {
    // 0x920
    return alarm(seconds);
}

// Address range: 0x930 - 0x936
int32_t function_930(int32_t fd, int64_t * buf, int32_t nbytes) {
    // 0x930
    return read(fd, buf, nbytes);
}

// Address range: 0x940 - 0x946
int32_t function_940(char * nptr) {
    // 0x940
    return atoi(nptr);
}

// Address range: 0x950 - 0x956
void function_950(int32_t status) {
    // 0x950
    exit(status);
}

// Address range: 0x960 - 0x966
void function_960(int64_t * d) {
    // 0x960
    __cxa_finalize(d);
}

// Address range: 0x970 - 0x99b
int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x970
    int64_t v1; // 0x970
    __libc_start_main(4018, (int32_t)a4, (char **)&v1, (void (*)())4064, (void (*)())0x1050, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x9a0 - 0x9d2
int64_t function_9a0(void) {
    // 0x9a0
    return 0x202010;
}

// Address range: 0x9e0 - 0xa22
int64_t function_9e0(void) {
    // 0x9e0
    return 0;
}

// Address range: 0xa30 - 0xa6a
int64_t function_a30(void) {
    // 0xa30
    if (g6 != 0) {
        // 0xa68
        int64_t result; // 0xa30
        return result;
    }
    // 0xa39
    if (*(int64_t *)0x201ff8 != 0) {
        // 0xa47
        __cxa_finalize((int64_t *)*(int64_t *)0x202008);
    }
    int64_t result2 = function_9a0(); // 0xa53
    g6 = 1;
    return result2;
}

// Address range: 0xa70 - 0xa7a
int64_t function_a70(void) {
    // 0xa70
    return function_9e0();
}

// Address range: 0xa7a - 0xa90
int64_t function_a7a(int64_t a1, int64_t a2) {
    int32_t v1 = a1; // 0xa7e
    int32_t v2 = v1 - (int32_t)a2; // 0xa87
    int64_t v3 = v2 == 0 | v2 < 0 != ((v2 ^ v1) & (int32_t)(a2 ^ a1)) < 0 ? a1 : a2; // 0xa8a
    return v3 & 0xffffffff;
}

// Address range: 0xa90 - 0xb7d
int64_t function_a90(void) {
    // 0xa90
    alarm(60);
    setbuf(g4, NULL);
    setbuf(g3, NULL);
    setbuf(g5, NULL);
    int64_t v1 = (int64_t)mmap(NULL, 0x2000, 3, 34, 0, 0); // 0xafa
    g9 = v1;
    g8 = (char *)&g14;
    g11 = (char *)&g14;
    g10 = (char *)(v1 + 0x1800);
    g12 = (int64_t)mmap(NULL, 0x1000, 3, 34, 0, 0);
    return puts("Welcome to Guess Game!");
}

// Address range: 0xb7d - 0xbfa
int64_t function_b7d(int64_t * a1, int64_t a2) {
    int64_t v1 = (int64_t)a1;
    uint32_t v2 = (int32_t)a2; // 0xbf2
    uint32_t v3 = 0;
    int64_t result; // 0xbd0
    while (v3 < v2) {
        int32_t v4 = read(0, (int64_t *)((int64_t)v3 + v1), v2 - v3) + v3; // 0xbc0
        result = v1 - 1 + (int64_t)v4;
        char * v5 = (char *)result;
        if (*v5 == 10) {
            // 0xbda
            *v5 = 0;
            return result;
        }
        v3 = v4;
    }
    // 0xbf7
    result = v3;
  lab_0xbf7:
    // 0xbf7
    return result;
}

// Address range: 0xbfa - 0xc44
int64_t function_bfa(void) {
    int64_t v1 = __readfsqword(40); // 0xc02
    int64_t str; // bp-40, 0xbfa
    function_b7d(&str, 15);
    int64_t str_as_i = atoi((char *)&str); // 0xc3b
    if (v1 != __readfsqword(40)) {
        // 0xc3d
        __stack_chk_fail();
        str_as_i = &g16;
    }
    // 0xc42
    return str_as_i;
}

// Address range: 0xc44 - 0xe65
int64_t function_c44(int64_t a1) {
    int64_t v1 = 0x100000000 * a1 / 0x100000000; // 0xc4c
    printf("Input your guess:");
    function_b7d((int64_t *)g11, a1 & 0xffffffff);
    if (v1 != (int64_t)strlen(g11)) {
        // 0xc90
        puts("Wrong Len");
        // 0xe63
        return 0;
    }
    // 0xca6
    memset((int64_t *)g8, 0, (int32_t)&g14);
    memset((int64_t *)g9, 0, (int32_t)&g14);
    int32_t v2 = v1; // 0xdd3
    int32_t v3 = 0; // 0xdd6
    if (v2 > 0) {
        int64_t v4 = 0;
        int32_t v5 = 0;
        unsigned char v6 = *(char *)(v4 + (int64_t)g11); // 0xd09
        int32_t * v7 = (int32_t *)(g9 - 4 + 4 * (int64_t)v6); // 0xd1a
        *v7 = *v7 + 1;
        unsigned char v8 = *(char *)(v4 + (int64_t)g10); // 0xd60
        int32_t * v9 = (int32_t *)((int64_t)g8 - 4 + 4 * (int64_t)v8); // 0xd71
        *v9 = *v9 + 1;
        char v10 = *(char *)(v4 + (int64_t)g11); // 0xdaf
        char v11 = *(char *)(v4 + (int64_t)g10); // 0xdc1
        v5 += (int32_t)(v10 == v11);
        v4++;
        v3 = v5;
        while (v4 != (v1 & 0xffffffff)) {
            // 0xcf2
            v6 = *(char *)(v4 + (int64_t)g11);
            v7 = (int32_t *)(g9 - 4 + 4 * (int64_t)v6);
            *v7 = *v7 + 1;
            v8 = *(char *)(v4 + (int64_t)g10);
            v9 = (int32_t *)((int64_t)g8 - 4 + 4 * (int64_t)v8);
            *v9 = *v9 + 1;
            v10 = *(char *)(v4 + (int64_t)g11);
            v11 = *(char *)(v4 + (int64_t)g10);
            v5 += (int32_t)(v10 == v11);
            v4++;
            v3 = v5;
        }
    }
    int32_t v12 = 0; // 0xe1a
    for (int64_t i = 0; i < 254; i++) {
        int64_t v13 = 4 * i; // 0xdf2
        uint32_t v14 = *(int32_t *)(v13 + (int64_t)g8); // 0xdf9
        uint32_t v15 = *(int32_t *)(g9 + v13); // 0xe0f
        v12 += (int32_t)function_a7a((int64_t)v15, (int64_t)v14);
    }
    int64_t result; // 0xc44
    if (v3 != v2) {
        // 0xe45
        printf("%dA%dB\n", (int64_t)v3, (int64_t)v12);
        result = 0;
    } else {
        // 0xe32
        puts("Good Guess!");
        result = 1;
    }
    // 0xe63
    return result;
}

// Address range: 0xe65 - 0xef9
int64_t function_e65(void) {
    // 0xe65
    puts("Thank you for playing the game");
    printf("Input the len of your name:");
    int64_t v1 = function_bfa(); // 0xe8f
    printf("Input your name:");
    function_b7d((int64_t *)&g13, v1 & 0xffffffff);
    printf("Input your comment:");
    function_b7d((int64_t *)g12, 0x1000);
    return printf("Bye! %s!", (char *)&g13);
}

// Address range: 0xef9 - 0xfb2
int64_t function_ef9(void) {
    // 0xef9
    printf("Input the len of your answer:");
    int64_t v1 = function_bfa(); // 0xf17
    int32_t v2 = v1; // 0xf1c
    if (v2 < 0 || v2 > (int32_t)&g15) {
        // 0xf2e
        puts("Wrong Len!");
        exit(-1);
        // UNREACHABLE
    }
    // 0xf44
    printf("Input your answer:");
    function_b7d((int64_t *)&g7, v1 & 0xffffffff);
    strcpy(g10, (char *)&g7);
    int32_t v3 = 0; // 0xf9f
    int64_t result = function_c44((int64_t)strlen(g10)); // 0xf96
    while (v3 < 299 == (int32_t)result == 0) {
        // 0xf85
        v3++;
        result = function_c44((int64_t)strlen(g10));
    }
    // 0xfaf
    return result;
}

// Address range: 0xfb2 - 0xfde
int64_t function_fb2(void) {
    // 0xfb2
    function_a90();
    function_ef9();
    function_e65();
    _exit(0);
    // UNREACHABLE
}

// Address range: 0xfe0 - 0x1045
int64_t function_fe0(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = function_868(); // 0x100c
    if ((int64_t)&g2 - (int64_t)&g1 >> 3 == 0) {
        // 0x1036
        return result;
    }
    int64_t v1 = 0; // 0x1014
    while (v1 + 1 != (int64_t)&g2 - (int64_t)&g1 >> 3) {
        // 0x1020
        v1++;
    }
    // 0x1036
    return result;
}

// Address range: 0x1050 - 0x1052
int64_t function_1050(void) {
    // 0x1050
    int64_t result; // 0x1050
    return result;
}

// Address range: 0x1054 - 0x105d
int64_t function_1054(void) {
    // 0x1054
    int64_t result; // 0x1054
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// void __stack_chk_fail(void);
// void _exit(int status);
// unsigned int alarm(unsigned int seconds);
// int atoi(const char * nptr);
// void exit(int status);
// void * memset(void * s, int c, size_t n);
// void * mmap(void * addr, size_t len, int prot, int flags, int fd, __off_t offset);
// int printf(const char * restrict format, ...);
// int puts(const char * s);
// ssize_t read(int fd, void * buf, size_t nbytes);
// void setbuf(FILE * restrict stream, char * restrict buf);
// char * strcpy(char * restrict dest, const char * restrict src);
// size_t strlen(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 31
