//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t stage1(void);

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL; // 0x601060
struct _IO_FILE * g2 = NULL; // 0x601070
struct _IO_FILE * g3 = NULL; // 0x601080

// ------------------------ Functions -------------------------

// Address range: 0x40079c - 0x400815
int64_t stage1(void) {
    int64_t buf = 0; // bp-56, 0x4007ab
    puts("Stage1");
    read(0, &buf, 256);
    puts("stage1 failed.");
    exit(-1);
    // UNREACHABLE
}

// Address range: 0x400815 - 0x400870
int main(int argc, char ** argv) {
    // 0x400815
    setbuf(g2, NULL);
    setbuf(g1, NULL);
    setbuf(g3, NULL);
    puts("Stack Overflooooow");
    stage1();
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// void exit(int status);
// int puts(const char * s);
// ssize_t read(int fd, void * buf, size_t nbytes);
// void setbuf(FILE * restrict stream, char * restrict buf);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 2
