//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <unistd.h>

// ------------------- Function Prototypes --------------------

int64_t entry_point(void);
int64_t function_1000(void);
int64_t function_1003(void);
int64_t function_1060(int64_t a1);
void function_1063(int64_t * d);
int64_t function_1070(int64_t a1, int64_t a2, int32_t a3, int32_t a4);
int32_t function_1073(int32_t rgid, int32_t egid, int32_t sgid);
int64_t function_1080(void);
int32_t function_1083(void);
int64_t function_1090(int64_t a1, int64_t a2);
int32_t function_1093(char * file, char * argv[1]);
int64_t function_10a3(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t function_1100(void);
int64_t function_1143(void);
int64_t function_1180(void);
int64_t function_1183(void);
int64_t function_118c(int64_t a1, int64_t a2);
int64_t function_11e0(void);
int64_t function_11e3(void);
int64_t function_11f3(int64_t a1, int64_t a2, int64_t a3);
int64_t function_1263(void);
int64_t function_126b(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0x1180; // 0x3da8
int64_t g2 = 0x1140; // 0x3db0
int64_t g3 = 0; // 0x4010
int32_t g4;

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x1001
int64_t function_1000(void) {
    // 0x1000
    int64_t result; // 0x1000
    return result;
}

// Address range: 0x1003 - 0x101b
int64_t function_1003(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x3fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g4;
    }
    // 0x1016
    return result;
}

// Address range: 0x1060 - 0x1061
int64_t function_1060(int64_t a1) {
    // 0x1060
    int64_t result; // 0x1060
    return result;
}

// Address range: 0x1063 - 0x106b
void function_1063(int64_t * d) {
    // 0x1063
    __cxa_finalize(d);
}

// Address range: 0x1070 - 0x1071
int64_t function_1070(int64_t a1, int64_t a2, int32_t a3, int32_t a4) {
    // 0x1070
    int64_t result; // 0x1070
    return result;
}

// Address range: 0x1073 - 0x107b
int32_t function_1073(int32_t rgid, int32_t egid, int32_t sgid) {
    // 0x1073
    return setresgid(rgid, egid, sgid);
}

// Address range: 0x1080 - 0x1081
int64_t function_1080(void) {
    // 0x1080
    int64_t result; // 0x1080
    return result;
}

// Address range: 0x1083 - 0x108b
int32_t function_1083(void) {
    // 0x1083
    return getegid();
}

// Address range: 0x1090 - 0x1091
int64_t function_1090(int64_t a1, int64_t a2) {
    // 0x1090
    int64_t result; // 0x1090
    return result;
}

// Address range: 0x1093 - 0x109b
int32_t function_1093(char * file, char * argv[1]) {
    // 0x1093
    return execvp(file, argv);
}

// Address range: 0x10a0 - 0x10a1
int64_t entry_point(void) {
    // 0x10a0
    int64_t result; // 0x10a0
    return result;
}

// Address range: 0x10a3 - 0x10f9
int64_t function_10a3(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x10a3
    int64_t v1; // 0x10a3
    __libc_start_main(0x1189, (int32_t)a4, (char **)&v1, (void (*)())0x11f0, (void (*)())0x1260, (void (*)())a3);
    __asm_hlt();
    return &g3;
}

// Address range: 0x1100 - 0x1139
int64_t function_1100(void) {
    // 0x1100
    return 0;
}

// Address range: 0x1143 - 0x1179
int64_t function_1143(void) {
    // 0x1143
    if (*(char *)&g3 != 0) {
        // 0x1178
        int64_t result; // 0x1143
        return result;
    }
    // 0x114d
    int64_t result2; // 0x1143
    if (*(int64_t *)0x3ff8 != 0) {
        // 0x115b
        result2 = function_1060(*(int64_t *)0x4008);
    }
    // 0x1167
    *(char *)&g3 = 1;
    return result2;
}

// Address range: 0x1180 - 0x1181
int64_t function_1180(void) {
    // 0x1180
    int64_t result; // 0x1180
    return result;
}

// Address range: 0x1183 - 0x1189
int64_t function_1183(void) {
    // 0x1183
    return function_1100();
}

// Address range: 0x118c - 0x11e0
int64_t function_118c(int64_t a1, int64_t a2) {
    int64_t v1 = function_1080(); // 0x119c
    int32_t v2 = v1; // 0x11a1
    int64_t v3 = v1 & 0xffffffff; // 0x11ad
    function_1070(v3, v3, v2, v2);
    function_11e0();
    int64_t v4 = a2 + 8; // 0x11bf
    function_1090(*(int64_t *)v4, v4);
    return 0;
}

// Address range: 0x11e0 - 0x11e1
int64_t function_11e0(void) {
    // 0x11e0
    int64_t result; // 0x11e0
    return result;
}

// Address range: 0x11e3 - 0x11eb
int64_t function_11e3(void) {
    // 0x11e3
    int64_t result; // 0x11e3
    return result;
}

// Address range: 0x11f3 - 0x1255
int64_t function_11f3(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = function_1000(); // 0x121c
    if ((int64_t)&g2 - (int64_t)&g1 >> 3 == 0) {
        // 0x1246
        return result;
    }
    int64_t v1 = 0; // 0x1225
    while (v1 + 1 != (int64_t)&g2 - (int64_t)&g1 >> 3) {
        // 0x1230
        v1++;
    }
    // 0x1246
    return result;
}

// Address range: 0x1263 - 0x1265
int64_t function_1263(void) {
    // 0x1263
    int64_t result; // 0x1263
    return result;
}

// Address range: 0x126b - 0x1275
int64_t function_126b(void) {
    // 0x126b
    int64_t result; // 0x126b
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// int execvp(const char * file, char * const argv[]);
// __gid_t getegid(void);
// int setresgid(__gid_t rgid, __gid_t egid, __gid_t sgid);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.3.0)
// Detected functions: 22
